version: "3"

services:
  db:
    build: ./db
    container_name: db_container
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - erpisi_network

  backend:
    depends_on:
      - db
    build: ./backend
    container_name: backend_container
    restart: always
    networks:
      - erpisi_network
    environment:
      DB_HOST: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - './backend:/backend'
    ports:
      - "8080:8080"
    develop:
      watch:
      - path: ./backend/src
        action: rebuild

volumes:
  pgdata:

networks:
  erpisi_network:
    driver: bridge